---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: task-prod
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0
spec:
  releaseName: task-prod
  chart:
    git: git@github.com:kfirosb/fluxcd_portfolio.git
    path: charts/taskapp
    ref: master
  values:
    image:
      repository: public.ecr.aws/t9c2t0n2/tasksapp
      tag: 1.0.22
    replicaCount: 1
    hpa:
      enabled: false
