apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: account-key-prod
  namespace:  default
spec:
  dnsNames:
    - taskappkfir.tk
  secretName: kfirsecret
  issuerRef:
    name: account-key-prod
    # kind: Issuer
  emailAddresses:
    - kfirosb@gmail.com
  