apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kfirsecret
  namespace:  default
spec:
  dnsNames:
    - a4992ad0040be424ead50b6da94480c0-67163295.eu-west-1.elb.amazonaws.com
  secretName: kfirsecret
  issuerRef:
    name: account-key-prod
    kind: ClusterIssuer
  