apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: account-key-prod
  namespace: default
spec:
  acme:
    # Staging API
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kfirosb@gmail.com
    privateKeySecretRef:
      name: account-key-prod
    solvers:
    - http01:
       ingress:
        # Valid values are ClusterIP and NodePort
        class: nginx
      