apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"    
    cert-manager.io/issuer: "account-key-prod"
spec:
  tls:
  - hosts:
    - taskappkfir.tk
    secretName: bla
  rules:
  - host: taskappkfir.tk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: taskapp
            port:
              number: 80

