apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  DATABASE_URL: 'mongodb://root:root@{{ .Release.Name }}-mongodb-0.{{ .Release.Name }}-mongodb-headless:27017,{{ .Release.Name }}-mongodb-1.{{ .Release.Name }}-mongodb-headless:27017,{{ .Release.Name }}-mongodb-2.{{ .Release.Name }}-mongodb-headless:27017/admin'
